# Test 55555 :) First command of everything is "Hello World"

In [ ]:
print("Hello world")

Hello world


# Variables and Types
specific, case-sensitive name
call up value through vaiable name


In [ ]:
height = 1.79
weight = 68.7

In [ ]:
height

1.79

In [ ]:
print(height)

1.79


Calculate BMI => formulas: BMI = weight/height^2

In [ ]:
bmi = weight/height ** 2
print(bmi)

21.44127836209856


หรือจะใช้ library math ก็ได้
เริ่มจาก import library math
math.pow(x,y)
โดยที่ x คือค่าที่ถูก y ยกกำลัง
return float value

In [ ]:
import math #import math library
bmi = weight/math.pow(height,2)
print(bmi)
print(type(bmi))

21.44127836209856
<class 'float'>


# Types
สามารถทราบ types ด้วยคำสั่ง type(variabile_name/value)
- integer number (int) 
- string, text (str) => จะใช้ ' ' หรือ " " ได้เหมือนกัน
- float - real numbers (float)
- dictionary - key,value (dict)
- list (list) ข้อมูลใน list ไม่จำเป็นต้องเป็นประเภทเดียวกันหมด คนละ ype ก็ได้ เช่น ชื่อคน ค่าความสูง
- boolean - True, False (bool)

In [ ]:
print(bmi)

21.44127836209856


In [ ]:
day_of_week = 5
print(type(day_of_week))

<class 'int'>


In [ ]:
x = "body mass index"
y = 'this works too'
print("type of x is {0} and msg is {1}, type of y is {2} and msg is {3}".format(type(x), x, type(y), y))

type of x is <class 'str'> and msg is body mass index, type of y is <class 'str'> and msg is this works too


In [ ]:
z = True
print(type(z))

<class 'bool'>


string มีคุณสมบัติการบวก

In [ ]:
ans_int = 2 + 3
print("type: ", type(ans_int),"ans: ", ans_int)

ans_str = 'ab' + 'cd'
print("type: ", type(ans_str),"ans: ", ans_str)

type:  <class 'int'> ans:  5
type:  <class 'str'> ans:  abcd


# List

In [ ]:
height_fam = ["liza",1.73, "emma", 1.68, "mom", 1.71, "data", 1.89] #list , ใน list ไม่จำเป็นต้องเป็นข้อมูล type เดียวกัน
print(height_fam)
print(type(height_fam))
height_fam_2 = [["liza", 1.73], ["emma", 1.68], ["mom", 1.71], ["data", 1.89]] #list in list
print(height_fam_2, "get value of index at 0 :", height_fam_2[0])
print('name: ', height_fam_2[0][0], 'height: ', height_fam_2[0][1])
print(type(height_fam_2))

['liza', 1.73, 'emma', 1.68, 'mom', 1.71, 'data', 1.89]
<class 'list'>
[['liza', 1.73], ['emma', 1.68], ['mom', 1.71], ['data', 1.89]] get value of index at 0 : ['liza', 1.73]
name:  liza height:  1.73
<class 'list'>



# Subsetting Lists
index start at 0 

การเข้าถึงค่าใน list เริ่มจาก index ที่ 0


In [ ]:
fam = ["liza",1.73, "emma", 1.68, "mom", 1.71, "data", 1.89] 
print(fam)

['liza', 1.73, 'emma', 1.68, 'mom', 1.71, 'data', 1.89]


In [ ]:
print(fam) # all of data in fam list
print(fam[0]) #liza
print(fam[1]) #height of liza
print(fam[-1], fam[7]) #last value!! / to the end of list เขียนได้ทั้งสองแบบ -1 หรือตัวสุดท้าย

['liza', 1.73, 'emma', 1.68, 'mom', 1.71, 'data', 1.89]
liza
1.73
1.89 1.89


List Slicing มักพบบ่อยใน for

[Start (inclusive) นับ : End (exclusive) ไม่นับ]

[: 4] เริ่มจากตัวแรกคือ 0 ถือตัวที่ 3

[5:] เริ่มจากตัวที่ 5 ถึงตัดสุดท้าย 

In [ ]:
print(fam[3:5]) #ลำดับที่ 3-4 คือ 1.68, mom
print(fam[1:4]) #ลำดับที่ 1-3 คือ 1.73, emma, 1.68
print(fam[:4]) # 0 ถึง 3 คือ liza, 1.73, emma, 1.68
print(fam[5:]) #5 ถึงสุดท้าย คือ 1.71, data, 1.89

[1.68, 'mom']
[1.73, 'emma', 1.68]
['liza', 1.73, 'emma', 1.68]
[1.71, 'data', 1.89]


In [ ]:
alphabet = [["a","b","c"],
            ["d","e","f"],
            ["g","h","i"]]
print(alphabet[2][0]) # g
print(alphabet[2][:2]) # g, h

g
['g', 'h']


# List Manipulation การจัดการ list


*   Change list element สามารถระบุ index เพื่อเข้าถึงค่า หรือเปลี่ยนแปลงค่าใน list ได้เลย เช่น fam[7] = 1.86
*   Add list element
*   Remove list element




In [ ]:
#Change List Element
family_height = ["nut", 1.56, "dad", 1.65, "mom", 1.65]
print(family_height)
family_height[-1] = 1.67 # update value
print(family_height)
family_height[0:2] = ['nutzhiii', 1.57] # nutzhiii, 1.57 # update value
print(family_height)

['nut', 1.56, 'dad', 1.65, 'mom', 1.65]
['nut', 1.56, 'dad', 1.65, 'mom', 1.67]
['nutzhiii', 1.57, 'dad', 1.65, 'mom', 1.67]


In [ ]:
#Add list element
family_height = family_height + ["sister", 1.56]
print(family_height)
family_height[8:10] = ["brother", 178]
print(family_height) 

['nutzhiii', 1.57, 'dad', 1.65, 'mom', 1.67, 'sister', 1.56]
['nutzhiii', 1.57, 'dad', 1.65, 'mom', 1.67, 'sister', 1.56, 'brother', 178]


In [ ]:
#delete element
family_del = family_height.copy() # copy value for testing
del(family_del[0:2])
print("del: ", family_del) #del nutzhiii, 1.57
print("origin: ", family_height) #origin

del:  ['dad', 1.65, 'mom', 1.67, 'sister', 1.56, 'brother', 178]
origin:  ['nutzhiii', 1.57, 'dad', 1.65, 'mom', 1.67, 'sister', 1.56, 'brother', 178]


# Behind the scenes (copy list to list)
เรียกว่าอะไรแล้ว จำไม่ได้ ขอแปะไว้ก่อน

In [ ]:
x_list = ["a","b","c"]
y_list = x_list # คือการที่เรา point y_list variable ไปที่ address ของ x_list เมื่อเราแก้ไขค่าจากตัวแปรใด ๆ ทั้ง y_list, x_list จะได้รับผลกระทบ เนื่องจากเก็บ address ที่เดียวกัน
y_list[1] = "z"
print("y is ", y_list) # เปลี่ยนจาก b to z
print("x is ", x_list) # เปลี่ยนจาก b to z แม้ไม่ได้เขียน เนื่องจากเก็บ address ที่เดียวกับ y_list

y is  ['a', 'z', 'c']
x is  ['a', 'z', 'c']


หากต้องการ copy ค่าของ list เพื่อไม่ให้กระทบกัน ทำตามนี้

In [ ]:
x_list = ["a","b","c"]
y_list = list(x_list) # สร้าง list จากค่า x_list
y_list[1] = "z"
print("y is ", y_list) # เปลี่ยนจาก b to z => a z c
print("x is ", x_list) # ได้ค่า a b c ไม่เปลี่ยนแปลง 

y is  ['a', 'z', 'c']
x is  ['a', 'b', 'c']


In [ ]:
# หรือ copy ค่ามาได้เช่น
x_list = ["a","b","c"]
y_list = x_list.copy() # copy ค่า x_list
y_list[1] = "z"
print("y is ", y_list) # เปลี่ยนจาก b to z => a z c
print("x is ", x_list) # ได้ค่า a b c ไม่เปลี่ยนแปลง 

y is  ['a', 'z', 'c']
x is  ['a', 'b', 'c']


#Functions

In [ ]:
height = [1.73, 1.68, 1.71, 1.89]
print(height)

[1.73, 1.68, 1.71, 1.89]


In [ ]:
#find max value
maximum = max(height) # maximum function
print(maximum)

1.89


In [ ]:
# round ปัดเศษ หากใส่แค่พารามิเตอร์เดียวจะ return integer หากใส่ 2 พารามิเตอร์ จะคืนทศนิยมตามจำนวนนั้น จะปัดเศษตามนี้คือ =5 >5 ปัดขึ้น <5 ปัดลง
value = round(1.68)
print(value) # 2
value = round(1.68, 1) 
print(value) # 1.7
# when the (ndigit+1)th digit is =5
print(round(2.665, 2))
# when the (ndigit+1)th digit is >=5
print(round(2.676, 2))
# when the (ndigit+1)th digit is <5
print(round(2.673, 2))

2
1.7
2.67
2.68
2.67


# Methods
มันคือ Functionas that belong to objects; ฟังก์ชันของ object 

เช่น str ก็มี method replace() upper() lower() เป็นของตัวเอง 

list ก็มี index(), count(), append

Everything = Object

Object have methods associated,depending on type

In [ ]:
#list method
family_height = ["nut", 1.56, "dad", 1.65, "mom", 1.65]
print("index at :", family_height.index("nut")) #หา index ที่มี value "nut" จะได้ 0
print("count: ", family_height.count(1.65)) # นับ index ที่มีค่าเท่ากับ 1.65 จะได้ 2 
family_height.append("sister")
family_height.append(1.56)
print(family_height)

index at : 0
count:  2
['nut', 1.56, 'dad', 1.65, 'mom', 1.65, 'sister', 1.56]


In [ ]:
#str method
sister = "liza"
print(sister.capitalize()) #ตัวแรกใหญ่
print(sister.upper()) #ตัวใหญ่หมด
print(sister.lower()) #ตัวเล็กหมด
print(sister.replace("a", "a narak")) # แทนที่ str
#sister have type is the string when we use a method index() it will return index of character in the string.
print(sister.index("z")) # 2
#but family_height have type is the list when we use a method index()  it will return index of value in the list.
print(family_height.index("mom")) # 4  

Liza
LIZA
liza
4
liza narak
2
4


# Packages
* ตัวอย่าง package ที่พร้อมให้เราใช้งานเช่น Numpy, Matplotlib, Scikit-learn
เพื่อช่วยในเรื่องของความสะดวก ไม่ต้องมา maintenance โคตรไม่เยอะ ไม่ยุ่งยากในการใช้งาน

* เราแค่ติดตั้งแต่เรียกใช้งาน เช่น pip3 install numpy หลังจากนั้นก็แค่ import numpy เรียกใช้ function ที่ต้องการ

* import numpy as np เป็นการย่อชื่อเรียกใช้ numpy ไม่ต้อง as np ตลอดก็ได้ แค่ขี้เกียจพิมพ์ numpy เต็ม หากใช้บ่อยมันยาว

In [ ]:
#pip install numpy #หากมีอยู่แล้วก็ไม่ต้องติดตั้ง 

In [ ]:
import numpy as np
array = np.array([1,2,3])
print(array)

[1 2 3]


In [ ]:
from numpy import array
#เรียกใช้แค่ function array มาใช้
array_numpy = array([1,2,3])
print(array_numpy)

[1 2 3]


In [ ]:
import numpy as np
array_np = np.array(["nut", 1.56, "dad", 1.65, "mom", 1.65])
print(array_np)
display(array_np)

['nut' '1.56' 'dad' '1.65' 'mom' '1.65']


array(['nut', '1.56', 'dad', '1.65', 'mom', '1.65'], dtype='<U4')

# Sorting

In [ ]:
#sort by asc and desc in list ใช้ได้กับทั้งตัวเลข ข้อความ
order_list = [20,10,5,15,9,15]
order_list.sort(reverse=True) # by descending order มากไปน้อย not return value, it changes the original list.
print(order_list)
order_list.sort() # by ascending order น้อยไปมาก
print(order_list)

[20, 15, 15, 10, 9, 5]
[5, 9, 10, 15, 15, 20]


In [ ]:
#หรือใช้เป็น functional ก็ได้ ถ้าไม่ใช่ method ของ list
desc_order = sorted(order_list, reverse=True) #return value, it not change the original list
asc_order = sorted(order_list)
print(desc_order)
print(asc_order) 

[5, 9, 10, 15, 15, 20]
[20, 15, 15, 10, 9, 5]
[5, 9, 10, 15, 15, 20]
[5, 9, 10, 15, 15, 20]


In [ ]:
#https://www.programiz.com/python-programming/methods/list/sort
#sorting using custom key
#note john hopkins is who invented "Hopkins statistic" that tendency calculation of data distribution in the cluster.
employees = [{'name': 'Alan Turing', 'age': 25, 'salary':10000},
             {'name': 'Sharon Lin', 'age': 30, 'salary':8000},
             {'name': 'John Hopkins', 'age': 18, 'salary':10000}, 
             {'name': 'Mikhil Tal', 'age': 40, 'salary':15000}] #dictionary 

def get_name(employee):
  return employee.get('name')

def get_age(employee):
  return employee.get('age')

def get_salary(employee):
  return employee.get('salary')

#sort by name (Ascending order) A to Z
employees.sort(key=get_name)
print(employees, end='\n\n')

#sort by age (Descending order) 
employees.sort(key=get_age, reverse=True)
print(employees, end='\n\n')

#sort by salary (Ascending order)
employees.sort(key=get_salary)
print(employees, end='\n\n')

# หากไม่ใช่ฟังก์ชัน get เราสามารถใช้ lambda เพื่อดึงเข้าถึงข้อมูลทุกค่าได้ ดังนี้
employees.sort(key=lambda x: x.get('name'))
print(employees, end='\n\n')

employees.sort(key=lambda x: x.get('age'),reverse=True)
print(employees, end='\n\n')

employees.sort(key=lambda x: x.get('salary'))
print(employees, end='\n\n')

#sort a tuple in list
point = [(2, 2), (3, 4), (4, 1), (1,3)]
point.sort(key=lambda x: x[1])
print(point)

[{'name': 'Alan Turing', 'age': 25, 'salary': 10000}, {'name': 'John Hopkins', 'age': 18, 'salary': 10000}, {'name': 'Mikhil Tal', 'age': 40, 'salary': 15000}, {'name': 'Sharon Lin', 'age': 30, 'salary': 8000}]

[{'name': 'Mikhil Tal', 'age': 40, 'salary': 15000}, {'name': 'Sharon Lin', 'age': 30, 'salary': 8000}, {'name': 'Alan Turing', 'age': 25, 'salary': 10000}, {'name': 'John Hopkins', 'age': 18, 'salary': 10000}]

[{'name': 'Sharon Lin', 'age': 30, 'salary': 8000}, {'name': 'Alan Turing', 'age': 25, 'salary': 10000}, {'name': 'John Hopkins', 'age': 18, 'salary': 10000}, {'name': 'Mikhil Tal', 'age': 40, 'salary': 15000}]

[{'name': 'Alan Turing', 'age': 25, 'salary': 10000}, {'name': 'John Hopkins', 'age': 18, 'salary': 10000}, {'name': 'Mikhil Tal', 'age': 40, 'salary': 15000}, {'name': 'Sharon Lin', 'age': 30, 'salary': 8000}]

[{'name': 'Mikhil Tal', 'age': 40, 'salary': 15000}, {'name': 'Sharon Lin', 'age': 30, 'salary': 8000}, {'name': 'Alan Turing', 'age': 25, 'salary': 100

# Numpy
* Numeric Python
* Alternative to python List: Numpy Array เป็นอีกทางเลือกหนึ่งสำหรับ list 
* Calculations over entire arrays สามารถคำนวณภายใน array ได้
* Easy and Fast ง่ายและรวดเร็ว
* pip3 install numpy

In [ ]:
import numpy as np
height = [1.73, 1.68, 1.71, 1.89, 1.79]
weight = [65.4, 59.2, 63.6, 88.4, 68.7]
np_height = np.array(height)
np_weight = np.array(weight)
print(np_height)
print(np_weight)
print(type(np_height), type(np_weight))

[1.73 1.68 1.71 1.89 1.79]
[65.4 59.2 63.6 88.4 68.7]
<class 'numpy.ndarray'> <class 'numpy.ndarray'>


In [ ]:
#calculate bmi in numpy array
bmi_array = np_weight / np_height ** 2 # สามารถคำนวณข้อมูลได้ทั้งชุด ในขณะที่ list ทำให้ไม่ได้ ต้องมาลัน loop แทน
print(bmi_array)
print(type(bmi_array))

[21.85171573 20.97505669 21.75028214 24.7473475  21.44127836]
<class 'numpy.ndarray'>


Numpy Subsetting

In [6]:
import numpy as np
bmi = np.array([21.852, 20.975, 21.75, 24.747, 21.441])
print(bmi)
print(bmi[1])
print(bmi > 23) # query value not get value return value is boolean, True = match condition, False = not match codition
print(bmi[bmi > 23]) #get value if match condition 
result_index = np.where(bmi > 23) #find index of numpy array when value match with condition
print(result_index[0]) # index

[21.852 20.975 21.75  24.747 21.441]
20.975
[False False False  True False]
[24.747]
[3]


In [8]:
#example: to convert a unit of height from meter into inch
import numpy as np
np_height_meter = np.array([1.73, 1.68, 1.71, 1.89, 1.79])
np_height_inch = np_height_meter * 39.37
print(np_height_inch)

[68.1101 66.1416 67.3227 74.4093 70.4723]


In [11]:
#example: assign value that y > 5 to x
import numpy as np
y = np.array([4,9,6,3,1])
print(y>5) #display boolean when match condition
x = y[y > 5] #get value 
print(x)
print(type(x))

[False  True  True False False]
[9 6]
<class 'numpy.ndarray'>


2D Numpy Arrays

In [18]:
np_2d = np.array([[1.73,1.68,1.71,1.89,1.79],
                  [65.4, 59.2, 63.6, 88.4, 68.7]])
print(np_2d)
print(np_2d.shape) # 2 rows, 5 columns มันคือการ get dimension ของ array มิติของข้อมูล
print(np_2d[0]) #get row ที่ 0 ทั้งหมด ทุก column np_2d[row,column]
print(np_2d[0][0], np_2d[0][1]) #get row = 0, column 0 1 ; 1.73, 1.68
print(np_2d[0,0:2]) #get row = 0, column 0 1 ; 1.73, 1.68 => np_2d[start row: end columns, start columns : end columns] ไม่ใส่อะไรเลยเท่ากับเอาหมด : คือ เอาหมด

[[ 1.73  1.68  1.71  1.89  1.79]
 [65.4  59.2  63.6  88.4  68.7 ]]
(2, 5)
[1.73 1.68 1.71 1.89 1.79]
1.73 1.68
[1.73 1.68]


#Numpy: Basic Statistics
* Get to know your data
* little data -> simply look at it
* Big data -> ?

**What is a mean, median, and mode**
https://greedisgoods.com/%E0%B8%84%E0%B9%88%E0%B8%B2%E0%B8%A1%E0%B8%B1%E0%B8%98%E0%B8%A2%E0%B8%90%E0%B8%B2%E0%B8%99-%E0%B8%84%E0%B8%B7%E0%B8%AD-median/

* Mean คือค่าเฉลี่ยประเภทหนึ่ง หาจากการนำเอาผลรวมของข้อมูลทั้งหมด / จำนวนของข้อมูลทั้งหมด

ตัวอย่าง นศ.ที่เรียนรายวิชาคณิตศาสตร์ section 1 มีทั้งหมด 5 คน แต่ละคนได้คะแนนสอบกลางภาค 

ได้แก่ 15, 12, 11, 10, 17 จากคะแนนเต็ม 30 คะแนน
หาค่าเฉลี่ยนคะแนนสอบกลางภาควิชาคณิตศาสตร์ของนศ. กลุ่มนี้จะได้

Mean(x) = (15+12+11+10+17) / 5 
Mean(x) = 65/5 = 13 
ดังนั้นค่าเฉลี่ยคะแนนสอบกลางภาคของนศ.กลุ่มนี้คือ 13 คะแนน จากคะแนนเต็ม 30 คะแนน หากตัดครึ่งที่ 15 คะแนนจาก 30 คะแนนหมายถึงสอบตกรายวิชานี้ เท่ากับว่ามีนิสิตสอบตกจำนวน 3 คน และผ่าน 2 คน

* Median คือค่ามัธยฐาน เป็นค่ากึ่งกลางของชุดข้อมูล โดยวิธีการหาเริ่มจาก 

เรียงข้อมูลก่อน **สำคัญมาก** แบ่งเป็น 2 กรณี

1. หากจำนวนข้อมูลเป็นจำนวนคี่ สามารถตอบได้เลยว่า median คือค่าที่เป็นลำดับกึ่งกลางของกลุ่มข้อมูล 
2. หากจำนวนข้อมูลเป็นจำนวนคู่ จะต้องนำ ผลรวมของข้อมูล 2 ข้อมูลที่อยู่ลำดับกึ่งกลางมาหาค่าเฉลี่ยน

ตย. จำนวนคี่ มี n = 7 => 12, 15, 16, 10 ,19, 10, 14

เรียงลำดับจะจากน้อยไปมาก มายไปน้อยก็ได้ 10, 10, 12, 14, 15, 16, 19

median = 14

ตย. จำนวนคู่ มี n = 8 => 10, 15, 13, 18, 14, 19, 11, 12

เรียง => 10, 11, 12, 13, 14, 15, 18, 19

median => (13+14) / 2 = 13.5 

* Mode คือฐานนิยม เลขที่มีความนิยมมากสุด => หา Frequency ของข้อมูล maximum of count of all data

ex. 4 **5** 1 **5** 2 **5** **5** 3 1 2 1 3 4 **5** 6 7 2 7 4 4 9 1 **5** 9 1
mode คือ 5 เนื่องจากมี count ที่ซ้ำกันมากสุดคือ 6 ครั้ง

**Tip เราสามารถหาฐานนิยมได้จาก** 

Mode = 3Median - 2Mean ไม่ค่อยตรงเลย แปะ **

In [31]:
#city-wide survey
import numpy as np
from scipy import stats
np_city = np.array([[1.64, 71.78],
                    [1.37, 63.35,],
                    [1.6, 55.09],
                    [2.04, 74.85],
                    [2.04, 68.72],
                    [2.01, 73.57]]) #asume own data for practicing => column => city1, city2 ; row is wide of location in city

#find mean of column 0
mean_city = np.mean(np_city[:,0]) # หาmeanของ data ด้วย numpy numpy.mean(numpy.ndarray) ** ค่าเฉลี่ย => sum of all value/ number of value คือ (1.64+1.37+...+2.01) / 6
print(mean_city) #1.7833333333333332

#find median of column 0
median_city = np.median(np_city[:,0]) #หา median มันคือมัธยฐานค่ากลางของชุดข้อมูล หลังจากที่คุณ sorted all the values ** ต้อง sorted ก่อนนะ สูตรคือผลรวม 2 ค่าตรงกลาง / 2 
print(median_city) # 

#find mode of column 0
mode_city = stats.mode(np_city[:,0])
print(mode_city) # info
print(mode_city[0]) #get value index 0 is value , index 1 is frequency

data = np.array([4, 5, 1, 5, 2, 5, 5, 3, 1, 2, 1, 3, 4, 5, 6, 7, 2, 7, 4, 4, 9, 1, 5, 9, 1])

mean = np.mean(data)
median = np.median(data)
mode = stats.mode(data)
print("mean, median, mode1, mode2 of this data set is", mean, median, mode[0], (3*median)-(2*mean))

1.7833333333333332
1.8249999999999997
ModeResult(mode=array([2.04]), count=array([2]))
[2.04]
mean, median, mode1, mode2 of this data set is 4.04 4.0 [5] 3.92


In [40]:
# Pearson correlation coefficients คุ้นๆ ลืมทฤษฎีแล้ว แปะ 
print(np.corrcoef(np_city[:,0], np_city[:,1])) # ระหว่างข้อมูล 2 matrix 
print(np.std(np_city[:,0])) #std ส่วนเบี่ยงเบนมาตรฐาน
print(np.sum(np_city)) # all data

[[1.         0.64924262]
 [0.64924262 1.        ]]
0.2608107018935807
418.06
[1.64 1.37 1.6  2.04 2.04 2.01]

[1.64 1.37 1.6  2.04 2.04 2.01]
